In [1]:
# Test whether you are able to print something
print 'Hi there! Machine Learning is very easy!! This workshop will teach you that!'

Hi there! Machine Learning is very easy!! This workshop will teach you that!


In [2]:
# This is a list in PYTHON. List is similar to an array!
List1 = [1,2,3]

In [8]:
# A for loop to print the elements in a list.
#
# NOTE: For first time users, there should be an indent in the second line!
# 
# TRY IT: Try removing the indent!
#
print 'Elements in the list are:';
for element in List1:
    print element,

Elements in the list are:
1 2 3


In [3]:
#Print another line - what is the change here ?
#NOTICE that you can use \n!
print '\nNumpy array:';

#IMPORT statement for getting NUMPY in.
import numpy as np;

#This is how we can create a NUMPY ARRAY
numpyArray = np.array([1,2,3,4]);

#Print the elements of the array
for element in numpyArray:
    print element;
    
#Directly print the array
print numpyArray;


Numpy array:
1
2
3
4
[1 2 3 4]


In [4]:
# LET'S DO IT TOGETHER:  
# a) Create 2 new numpy arrays and add them together. Print the result.
# b) Create 2 python lists and add them together. Print the result.


numpyArray2 = np.array([1,2,3,4]);
numpyArray3 = np.array([1,2,3,4]);



# This is how we can add the array
numpyArray4 = numpyArray2 + numpyArray3;

print "Numpy array:"
#print the array
for element in numpyArray4:
    print element;
    

# numpy array + 100 will add 100 to all the elements of the array
numpyArray6 = numpyArray4+100;
print numpyArray6
    
print '\n Output of List: '
List2 = [1,2,3,4]
List3 = [1,2,3,4]

#Add the lists together
List4 = List2 + List3

#print the list
for element in List4:
    print element;

numpyArray5 = [[1,2,3],[4,5,6],[7,8,9]]
numpyArray5[0][0]

numpyArray7 = np.array([[1,2,3],[4,5,6],[7,8,9]])
numpyArray8 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print  numpyArray7 + numpyArray8 

# see the difference between the below two lines
print np.dot(numpyArray7,numpyArray8)
print numpyArray7*numpyArray8


#notes:
# numpy array adds elements whereas list appends elements  



Numpy array:
2
4
6
8
[102 104 106 108]

 Output of List: 
1
2
3
4
1
2
3
4
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


## Check point ##

Numpy Array can be thought of as a MATRIX. The array which we created just now is a row matrix. Numpy helps in doing all matrix operations. 

Sample of MATRIX ADDITION is what we saw just now!

Try out creating an array like this: 

A = np.array([[1,2,3],[4,5,6],[7,8,9]]); 

This is printing a matrix of size 3 X 3.

##Exercises for later ##

Try out other MATRIX Operations - Subtraction, Dot Product, Multiplication! 

In [1]:
print("abc")

abc
